services:
  - type: web
    name: taskmaster-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py create_admin"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-netlify-app.netlify.app"
      - key: DATABASE_URL
        fromDatabase:
          name: taskmaster-db
          property: connectionString
      - key: ACCESS_TOKEN_LIFETIME
        value: "60"
      - key: REFRESH_TOKEN_LIFETIME
        value: "7"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "user@admin.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "Admin@123"
      - key: DJANGO_SUPERUSER_FIRST_NAME
        value: "admin"
      - key: DJANGO_SUPERUSER_LAST_NAME
        value: "user"

databases:
  - name: taskmaster-db
    databaseName: taskmaster
    user: taskmaster
    region: oregon
    plan: free
